import { Inter } from "next/font/google";
import Header from "../components/Header";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function DashboardLayout({ children }) {
  return (
      <main className={inter.className}>
        <Header />
        <div className="page_container container-fluid p-3">
          
          {children}
        </div>
      </main>
  );
}
